### ISSUE TITLE
create a HOW-CREATE-A-HOOK.md

### ISSUE THREAD

**Issue by tauantcamargo** [devthiago/react-ui-hooks#11]
We also need a guide to show how the developers can creating new hooks.

**Comment by devthiago** [comment]
Create a new react hook:

```bash
npm run generate:hook useModal
or
yarn generate:hook useModal
```

Create a new react hook unit test:

```bash
npm run generate:test useModal
or
yarn generate:test useModal
```

Create a new react hook doc:

```bash
npm run generate:docs useModal
or
yarn generate:docs useModal
```

Generate docs for all react hooks:

```bash
npm run generate:docs
or
yarn generate:docs
```

**Comment by devthiago** [comment]
All scripts files are in `/scripts` folder. Look at `/scripts/lib` and `/scripts/boilerplates` for more details.

**Comment by tauantcamargo** [comment]
@devthiago thanks I'm going to create this md :smile:

**Comment by devthiago** [comment]
@elainemattos is on this issue /cc @Lukyhenson

**Comment by devthiago** [comment]
@allcontributors please add @elainemattos for doc
