### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by devthiago** [devthiago/react-ui-hooks#2]
We need a guide to help developers creating new hooks.
Example: https://reactjs.org/docs/how-to-contribute.html

**Comment by tauantcamargo** [comment]
@devthiago i'm going to solve this issue, can u assignee to me?

**Comment by devthiago** [comment]
@all-contributors please add @devthiago for infrastructure and code

**Comment by tauantcamargo** [comment]
@devthiago i created this PR to solve this issue: [Docs/adding contributing quides to documentation](https://github.com/devthiago/react-ui-hooks/pull/6)

**Comment by devthiago** [comment]
@allcontributors please add @Lukyhenson  for doc
